# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# This is the minimum version number required.
fastlane_version "2.96.0"

default_platform :ios

platform :ios do
  before_all do |lane|
    ensure_git_status_clean
  end

  desc "Run library tests"
  lane :tests do
    Dir["*.xml"].each { |file|
      File.delete(file)
    }

    override_test_product_names

    output_style = FastlaneCore::Env.truthy?("TRAVIS") ? "raw" : "standard"

    scan(
      device: "iPhone 11",
      output_types: "",
      output_style: output_style,
      fail_build: false,
      clean: true
    )
    scan(
      device: "Apple TV",
      output_types: "",
      output_style: output_style,
      fail_build: false,
      clean: true
    )

    xcresults_path = lane_context[SharedValues::SCAN_DERIVED_DATA_PATH] + "/Logs/Test/"
    Dir.chdir(xcresults_path) do
      UI.user_error!("Whoops, there are not only two xcresult files in the derived data path.") if Dir["*.xcresult"].count != 2
    end

    trainer(
      path: xcresults_path,
      output_directory: "./fastlane"
    )
  end

  desc "Override test product names to split iOS and tvOS test results"
  private_lane :override_test_product_names  do
    set_xcconfig_value(
      path: 'Tests/Tests.xcconfig',
      name: 'PRODUCT_NAME[sdk=iphone*]',
      value: '$(PROJECT_NAME)-iOS'
    )
    set_xcconfig_value(
      path: 'Tests/Tests.xcconfig',
      name: 'PRODUCT_NAME[sdk=appletv*]',
      value: '$(PROJECT_NAME)-tvOS'
    )
  end

  after_all do |lane|
    reset_git_repo(skip_clean: true)
  end

  error do |lane, exception|
    clean_build_artifacts
    reset_git_repo(skip_clean: true, force: true)
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
